# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

target 'DailyBond' do
    pod 'Parse'
    pod 'ParseFacebookUtilsV4'
    pod 'FBSDKCoreKit'
    pod 'ParseUI'
    pod 'ParseCrashReporting'
    pod 'Bolts'
    pod 'BFTask-Extras'
end

target 'DailyBondTests' do

end

