# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

target 'DailyBond' do
    pod 'Parse'
    pod 'ParseFacebookUtilsV4'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKMessengerShareKit', '~> 1.2'
    pod 'ParseUI'
    pod 'ParseCrashReporting'
    pod 'Bolts'
    pod 'BFTask-Extras'
    pod 'MaryPopin'
    pod 'DateTools'
    pod 'MJExtension'
    pod 'SDWebImage'
    pod 'pop', '~> 1.0'
end

target 'DailyBondTests' do

end

